# Generated by Django 4.1 on 2022-08-30 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 7, 40, 5, 453198, tzinfo=datetime.timezone.utc)),
        ),
    ]
