# Generated by Django 4.1 on 2022-08-31 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahapp', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 10, 45, 3, 905071, tzinfo=datetime.timezone.utc)),
        ),
    ]
