# Generated by Django 4.1 on 2022-09-19 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahapp', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='problem',
            field=models.CharField(default=0, max_length=32000),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 6, 54, 55, 978458, tzinfo=datetime.timezone.utc)),
        ),
    ]
