# Generated by Django 4.0.6 on 2022-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahapp', '0004_users_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bojId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
