# Generated by Django 4.0.6 on 2022-07-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahapp', '0005_users_bojid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
